###
    # Customer Login
###
POST http://localhost:3000/api/auth/customer/login
Content-Type: application/json

{
    "phone" : "9820648212"
}


###
    # Verify OTP
###
POST http://localhost:3000/api/auth/customer/verify-otp
Content-Type: application/json

{
    "phone" : "9820648212",
    "otp" : "8067"
}


### Registration
POST http://127.0.0.1:3000/api/auth/customer/register
Content-Type: application/json

{
    "first_name": "Tes",
    "last_name": "TEst",
    "email": "test@joshfuels.com",
    "company": "TYS",
    "phone": "9210129012",
    "accept_term": "true"
}


### Get Profile
GET http://127.0.0.1:3000/api/auth/customer/getProfile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTI5MTcwMmMxM2Q4OThhNjk5M2QyMjkiLCJmaXJzdF9uYW1lIjoiQW5pbCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJyZXlhbnNoQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTgyMDY0ODIxMiIsImlzX3ByaXZpbGFnZWQiOmZhbHNlLCJpYXQiOjE2OTgzNTM5MDcsImV4cCI6MTY5ODk1ODcwN30.JjgYRDsr-k-HfVnNFzEKgK86aL8xPaIPSv6pGbMZpZY

### Update Profile
POST http://127.0.0.1:3000/api/auth/customer/updateProfile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGM5NjMxNzhmNWJmMTI2Njc3YzI0MmEiLCJmaXJzdF9uYW1lIjoiU2hpdmFtIiwibGFzdF9uYW1lIjoiR3VwdGEiLCJlbWFpbCI6ImFkbWluQGpvc2hmdWVscy5jb20iLCJwaG9uZSI6Ijg4NTA2NjQxOTEiLCJpYXQiOjE2OTY3NjkxMDAsImV4cCI6MTY5NzM3MzkwMH0.K0NRx1fEC8L0186YPz8OPKjftNEtXuWp3RUtqDR6KEQ

{    
    "email": "admin@joshfuels.com"
}

### Update Profile Photo 
POST http://127.0.0.1:3000/api/auth/customer/updatePhoto
Content-Type: application/json
Authorization: Bearer 

{    
    "first_name": "Anil"
}


### Add Address
POST http://localhost:3000/api/auth/customer/add-address
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTI5MTcwMmMxM2Q4OThhNjk5M2QyMjkiLCJmaXJzdF9uYW1lIjoiQW5pbCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJyZXlhbnNoQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTgyMDY0ODIxMiIsImlzX3ByaXZpbGFnZWQiOnRydWUsImlhdCI6MTY5ODM5NjI5MSwiZXhwIjoxNjk5MDAxMDkxfQ.RUvbrVJmoFHOShLHOtPnls04rLhNSHQAMk6-iUSGKiM

{
    "address_type" : "Office", 
    "address_1" : "S-58, Haware Fantasia, Behind Inorbit Mall", 
    "area" : "Vashi", 
    "city" : "Navi Mumbai", 
    "pincode" : "123455", 
    "state" : "Maharashtra", 
    "country" : "India"
}

### Get Address
GET http://localhost:3000/api/auth/customer/get-address
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTI5MTcwMmMxM2Q4OThhNjk5M2QyMjkiLCJmaXJzdF9uYW1lIjoiQW5pbCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJyZXlhbnNoQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTgyMDY0ODIxMiIsImlzX3ByaXZpbGFnZWQiOmZhbHNlLCJpYXQiOjE2OTgzNTM5MDcsImV4cCI6MTY5ODk1ODcwN30.JjgYRDsr-k-HfVnNFzEKgK86aL8xPaIPSv6pGbMZpZY

### Update Address
POST http://localhost:3000/api/auth/customer/update-address
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTI5MTcwMmMxM2Q4OThhNjk5M2QyMjkiLCJmaXJzdF9uYW1lIjoiQW5pbCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJyZXlhbnNoQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTgyMDY0ODIxMiIsImlzX3ByaXZpbGFnZWQiOmZhbHNlLCJpYXQiOjE2OTgzNTM5MDcsImV4cCI6MTY5ODk1ODcwN30.JjgYRDsr-k-HfVnNFzEKgK86aL8xPaIPSv6pGbMZpZY

{
    "address_id" : "650191993bd8b22339022421",
    "address_type" : "Office", 
    "address_1" : "S-58, Haware Fantasia, Behind Inorbit Mall", 
    "area" : "Vashi", 
    "city" : "Navi Mumbai", 
    "pincode" : "000000", 
    "state" : "Maharashtra", 
    "country" : "India"
}

### Deleted Address 
DELETE http://localhost:3000/api/auth/customer/delete-address
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTI5MTcwMmMxM2Q4OThhNjk5M2QyMjkiLCJmaXJzdF9uYW1lIjoiQW5pbCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJyZXlhbnNoQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTgyMDY0ODIxMiIsImlzX3ByaXZpbGFnZWQiOmZhbHNlLCJpYXQiOjE2OTgzNTM5MDcsImV4cCI6MTY5ODk1ODcwN30.JjgYRDsr-k-HfVnNFzEKgK86aL8xPaIPSv6pGbMZpZY

{
    "address_id" : "650191c73bd8b22339022427"
}


### Add Device
POST http://localhost:3000/api/auth/customer/add-device
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTI5MTcwMmMxM2Q4OThhNjk5M2QyMjkiLCJmaXJzdF9uYW1lIjoiQW5pbCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJyZXlhbnNoQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTgyMDY0ODIxMiIsImlzX3ByaXZpbGFnZWQiOmZhbHNlLCJpYXQiOjE2OTgzNTM5MDcsImV4cCI6MTY5ODk1ODcwN30.JjgYRDsr-k-HfVnNFzEKgK86aL8xPaIPSv6pGbMZpZY

{
    "name" : "shivam's iPhone",
    "type" : "iOS",
    "version" : "17.0.1"
}

### Fetch data 
Get http://localhost:3000/api/auth/customer/userdata
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTI5MTcwMmMxM2Q4OThhNjk5M2QyMjkiLCJmaXJzdF9uYW1lIjoiQW5pbCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJyZXlhbnNoQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTgyMDY0ODIxMiIsImlzX3ByaXZpbGFnZWQiOmZhbHNlLCJpYXQiOjE2OTgzNTM5MDcsImV4cCI6MTY5ODk1ODcwN30.JjgYRDsr-k-HfVnNFzEKgK86aL8xPaIPSv6pGbMZpZY

### LogOut
POST http://localhost:3000/api/auth/customer/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTI5MTcwMmMxM2Q4OThhNjk5M2QyMjkiLCJmaXJzdF9uYW1lIjoiQW5pbCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJyZXlhbnNoQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTgyMDY0ODIxMiIsImlzX3ByaXZpbGFnZWQiOmZhbHNlLCJpYXQiOjE2OTgzNTM5MDcsImV4cCI6MTY5ODk1ODcwN30.JjgYRDsr-k-HfVnNFzEKgK86aL8xPaIPSv6pGbMZpZY.eyJ1c2VySWQiOiI2NTFmYjNlODQxZWRlNjgxYzE2Y2Q3NTkiLCJmaXJzdF9uYW1lIjoiVGVzIiwibGFzdF9uYW1lIjoiVEVzdCIsImVtYWlsIjoidGVzdEBqb3NoZnVlbHMuY29tIiwicGhvbmUiOiI5MjEwMTI5MDEyIiwiaWF0IjoxNjk2NTc2NDg5LCJleHAiOjE2OTcxODEyODl9.CUa2Wi7sJKRuTp7NZVJ6kCN9Z3WgCQsR9FK5GoDunbg

