
########## Cart API ##########

### 
    # Show Cart
###
GET  http://localhost:3000/api/auth/cart/get
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTAxODFhYmY4NWU1MGNjMzQwNjdkZWQiLCJmaXJzdF9uYW1lIjoiRGVlcGFrIiwibGFzdF9uYW1lIjoiR3VwdGEiLCJlbWFpbCI6ImRlZXBha2d1cHRhQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTg3MDg3ODA0MSIsImlzX3ByaXZpbGFnZWQiOmZhbHNlLCJpYXQiOjE2OTk1MTkyNzAsImV4cCI6MTcwMDEyNDA3MH0.Lw7brk_I89rBwUC7c7E-iDq5VfyXawaV19AhqvCTwdA

### 
    # Add To Cart
###
POST http://localhost:3000/api/auth/cart/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTAxODFhYmY4NWU1MGNjMzQwNjdkZWQiLCJmaXJzdF9uYW1lIjoiRGVlcGFrIiwibGFzdF9uYW1lIjoiR3VwdGEiLCJlbWFpbCI6ImRlZXBha2d1cHRhQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTg3MDg3ODA0MSIsImlzX3ByaXZpbGFnZWQiOmZhbHNlLCJpYXQiOjE2OTk1MTkyNzAsImV4cCI6MTcwMDEyNDA3MH0.Lw7brk_I89rBwUC7c7E-iDq5VfyXawaV19AhqvCTwdA

{
    "product" : "64f6da5aed30c8f3d5765007",
    "quantity" : "192094"
}

### 
    # Update Cart Data
###
POST http://localhost:3000/api/auth/cart/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTAxODFhYmY4NWU1MGNjMzQwNjdkZWQiLCJmaXJzdF9uYW1lIjoiRGVlcGFrIiwibGFzdF9uYW1lIjoiR3VwdGEiLCJlbWFpbCI6ImRlZXBha2d1cHRhQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTg3MDg3ODA0MSIsImlzX3ByaXZpbGFnZWQiOmZhbHNlLCJpYXQiOjE2OTk1MTkyNzAsImV4cCI6MTcwMDEyNDA3MH0.Lw7brk_I89rBwUC7c7E-iDq5VfyXawaV19AhqvCTwdA

{
    "cart_id" : "652cc91b17c5dcafb2fa2c41",
    "product_id" : "64f6da5aed30c8f3d5765007",
    "quantity" : 215
}

### 
    # Delete Single Cart Data
###
POST http://localhost:3000/api/auth/cart/delete-item
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTAxODFhYmY4NWU1MGNjMzQwNjdkZWQiLCJmaXJzdF9uYW1lIjoiRGVlcGFrIiwibGFzdF9uYW1lIjoiR3VwdGEiLCJlbWFpbCI6ImRlZXBha2d1cHRhQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTg3MDg3ODA0MSIsImlzX3ByaXZpbGFnZWQiOmZhbHNlLCJpYXQiOjE2OTk1MTkyNzAsImV4cCI6MTcwMDEyNDA3MH0.Lw7brk_I89rBwUC7c7E-iDq5VfyXawaV19AhqvCTwdA

{
    "cart_id" : "6509f70778e25cf42012d7e8",
    "product_id" : "64f6da5aed30c8f3d5765007"
}

### 
    # Delete Cart Data
###
DELETE http://localhost:3000/api/auth/cart/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTAxODFhYmY4NWU1MGNjMzQwNjdkZWQiLCJmaXJzdF9uYW1lIjoiRGVlcGFrIiwibGFzdF9uYW1lIjoiR3VwdGEiLCJlbWFpbCI6ImRlZXBha2d1cHRhQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTg3MDg3ODA0MSIsImlzX3ByaXZpbGFnZWQiOmZhbHNlLCJpYXQiOjE2OTk1MTkyNzAsImV4cCI6MTcwMDEyNDA3MH0.Lw7brk_I89rBwUC7c7E-iDq5VfyXawaV19AhqvCTwdA

{
    "cart_id" : "653b78ef8467c46b6822bd54"
}

