### Send Email
POST http://localhost:3000/api/auth/customer/send-email
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGM5NjMxNzhmNWJmMTI2Njc3YzI0MmEiLCJmaXJzdF9uYW1lIjoiU2hpdmFtIiwibGFzdF9uYW1lIjoiR3VwdGEiLCJlbWFpbCI6ImFkbWluQGpvc2hmdWVscy5jb20iLCJwaG9uZSI6Ijg4NTA2NjQxOTEiLCJpc19wcml2aWxhZ2VkIjpmYWxzZSwiaWF0IjoxNjk3NTMxNjgwLCJleHAiOjE2OTgxMzY0ODB9.8g1-dYeG8_ZewetPXPH_JdPh-TYUnumUUvWxhomqVuM

### Send Notification
POST http://localhost:3000/admin/auth/settings/notification/send/65536969ab3d0499501b1c1b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGM5NjMxNzhmNWJmMTI2Njc3YzI0MmEiLCJmaXJzdF9uYW1lIjoiU2hpdmFtIiwidXNlcnR5cGUiOiJBZG1pbiIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhZG1pbkBqb3NoZnVlbHMuY29tIiwicGhvbmUiOiI4ODUwNjY0MTkxIiwicHJvZmlsZSI6ImRlZmF1bHRfcHJvZmlsZS5wbmciLCJpYXQiOjE2OTk5NjM2MjgsImV4cCI6MTcwMDAwNjgyOH0.ckk-pdrcIGUkpPqLBR1-AZtExQxWWqlSyAfXXY8HOqM

