### Send Email
POST http://localhost:3000/api/auth/customer/send-email
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGM5NjMxNzhmNWJmMTI2Njc3YzI0MmEiLCJmaXJzdF9uYW1lIjoiU2hpdmFtIiwibGFzdF9uYW1lIjoiR3VwdGEiLCJlbWFpbCI6InJ2c2hpdmFtc2FodS4xMjIyQGdtYWlsLmNvbSIsInBob25lIjoiODg1MDY2NDE5MSIsImlhdCI6MTY5Njg0Njc3NSwiZXhwIjoxNjk3NDUxNTc1fQ.I49vz4a5MGMrelx8lw6sgdiz-toW0HBPBMNDDq3_VNI
