### Send Email
POST http://localhost:3000/api/auth/customer/send-email
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGM5NjMxNzhmNWJmMTI2Njc3YzI0MmEiLCJmaXJzdF9uYW1lIjoiU2hpdmFtIiwibGFzdF9uYW1lIjoiR3VwdGEiLCJlbWFpbCI6ImFkbWluQGpvc2hmdWVscy5jb20iLCJwaG9uZSI6Ijg4NTA2NjQxOTEiLCJpc19wcml2aWxhZ2VkIjpmYWxzZSwiaWF0IjoxNjk3NTMxNjgwLCJleHAiOjE2OTgxMzY0ODB9.8g1-dYeG8_ZewetPXPH_JdPh-TYUnumUUvWxhomqVuM
