
###         # Order API  #       ###
## CREATE ORDER 
POST http://localhost:3000/api/auth/order/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTAxODFhYmY4NWU1MGNjMzQwNjdkZWQiLCJmaXJzdF9uYW1lIjoiRGVlcGFrIiwibGFzdF9uYW1lIjoiR3VwdGEiLCJlbWFpbCI6ImRlZXBha2d1cHRhQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTg3MDg3ODA0MSIsImlzX3ByaXZpbGFnZWQiOmZhbHNlLCJpYXQiOjE2OTk1MTkyNzAsImV4cCI6MTcwMDEyNDA3MH0.Lw7brk_I89rBwUC7c7E-iDq5VfyXawaV19AhqvCTwdA

{
    "address_id": "653b82b832b6784d8c5d99f9",
    "cart_id": "654c9b58dfd18578e1678940",
    "delivery_date": "19/11/2023",
    "delivery_time": "2:00 - 10:00",
    "payment_method": "Cash on Delivery",
    "note": "Keep the Diesels extra on;y",
    "total_price" : 19209400,
    "coupon_discount" : 100,
    "delivery_fee" : 0,
    "grand_total": 19209300

}


### GeT ORDER 
GET http://localhost:3000/api/auth/order/get
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTAxODFhYmY4NWU1MGNjMzQwNjdkZWQiLCJmaXJzdF9uYW1lIjoiRGVlcGFrIiwibGFzdF9uYW1lIjoiR3VwdGEiLCJlbWFpbCI6ImRlZXBha2d1cHRhQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTg3MDg3ODA0MSIsImlzX3ByaXZpbGFnZWQiOmZhbHNlLCJpYXQiOjE2OTk1MTkyNzAsImV4cCI6MTcwMDEyNDA3MH0.Lw7brk_I89rBwUC7c7E-iDq5VfyXawaV19AhqvCTwdA

### GeT Single ORDER 
GET http://localhost:3000/api/auth/order/get-order?page=1&perPage=10

Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTAxODFhYmY4NWU1MGNjMzQwNjdkZWQiLCJmaXJzdF9uYW1lIjoiRGVlcGFrIiwibGFzdF9uYW1lIjoiR3VwdGEiLCJlbWFpbCI6ImRlZXBha2d1cHRhQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTg3MDg3ODA0MSIsImlzX3ByaXZpbGFnZWQiOmZhbHNlLCJpYXQiOjE2OTk1MTkyNzAsImV4cCI6MTcwMDEyNDA3MH0.Lw7brk_I89rBwUC7c7E-iDq5VfyXawaV19AhqvCTwdA

{
    "order_id" : "100002"
}

### Cancel order
POST http://localhost:3000/api/auth/order/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTAxODFhYmY4NWU1MGNjMzQwNjdkZWQiLCJmaXJzdF9uYW1lIjoiRGVlcGFrIiwibGFzdF9uYW1lIjoiR3VwdGEiLCJlbWFpbCI6ImRlZXBha2d1cHRhQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTg3MDg3ODA0MSIsImlzX3ByaXZpbGFnZWQiOmZhbHNlLCJpYXQiOjE2OTk1MTkyNzAsImV4cCI6MTcwMDEyNDA3MH0.Lw7brk_I89rBwUC7c7E-iDq5VfyXawaV19AhqvCTwdA

{
    "order_id" : "100002"
}

### Update order
POST http://localhost:3000/api/auth/order/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTAxODFhYmY4NWU1MGNjMzQwNjdkZWQiLCJmaXJzdF9uYW1lIjoiRGVlcGFrIiwibGFzdF9uYW1lIjoiR3VwdGEiLCJlbWFpbCI6ImRlZXBha2d1cHRhQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTg3MDg3ODA0MSIsImlzX3ByaXZpbGFnZWQiOmZhbHNlLCJpYXQiOjE2OTk1MTkyNzAsImV4cCI6MTcwMDEyNDA3MH0.Lw7brk_I89rBwUC7c7E-iDq5VfyXawaV19AhqvCTwdA

{
    "order_id" : "100002",
    "product_id" : "64f6da85ed30c8f3d5765043",
    "quantity" : 100,
    "total_price" : 12385,
    "grand_total" : 22130
}   
