
###         # Order API  #       ###
## CREATE ORDER 
POST http://localhost:3000/api/auth/order/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTI5MTcwMmMxM2Q4OThhNjk5M2QyMjkiLCJmaXJzdF9uYW1lIjoiQW5pbCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJyZXlhbnNoQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTgyMDY0ODIxMiIsImlzX3ByaXZpbGFnZWQiOnRydWUsImlhdCI6MTY5ODM5NjI5MSwiZXhwIjoxNjk5MDAxMDkxfQ.RUvbrVJmoFHOShLHOtPnls04rLhNSHQAMk6-iUSGKiM

{
    "address_id": "653b82b832b6784d8c5d99f9",
    "cart_id": "654083a209a433c38a78f458",
    "delivery_date": "19/10/2023",
    "delivery_time": "2:00 - 10:00",
    "payment_method": "Cash on Delivery",
    "note": "Keep the Diesels extra on;y",
    "total_price" : 19209400,
    "coupon_discount" : 100,
    "delivery_fee" : 0,
    "grand_total": 19209300

}


### GeT ORDER 
GET http://localhost:3000/api/auth/order/get
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTI5MTcwMmMxM2Q4OThhNjk5M2QyMjkiLCJmaXJzdF9uYW1lIjoiQW5pbCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJyZXlhbnNoQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTgyMDY0ODIxMiIsImlzX3ByaXZpbGFnZWQiOnRydWUsImlhdCI6MTY5ODM5NjI5MSwiZXhwIjoxNjk5MDAxMDkxfQ.RUvbrVJmoFHOShLHOtPnls04rLhNSHQAMk6-iUSGKiM

### GeT Single ORDER 
GET http://localhost:3000/api/auth/order/get-order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTI5MTcwMmMxM2Q4OThhNjk5M2QyMjkiLCJmaXJzdF9uYW1lIjoiQW5pbCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJyZXlhbnNoQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTgyMDY0ODIxMiIsImlzX3ByaXZpbGFnZWQiOnRydWUsImlhdCI6MTY5ODM5NjI5MSwiZXhwIjoxNjk5MDAxMDkxfQ.RUvbrVJmoFHOShLHOtPnls04rLhNSHQAMk6-iUSGKiM

{
    "order_id" : "100002"
}

### Cancel order
POST http://localhost:3000/api/auth/order/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTI5MTcwMmMxM2Q4OThhNjk5M2QyMjkiLCJmaXJzdF9uYW1lIjoiQW5pbCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJyZXlhbnNoQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTgyMDY0ODIxMiIsImlzX3ByaXZpbGFnZWQiOnRydWUsImlhdCI6MTY5ODM5NjI5MSwiZXhwIjoxNjk5MDAxMDkxfQ.RUvbrVJmoFHOShLHOtPnls04rLhNSHQAMk6-iUSGKiM

{
    "order_id" : "100002"
}

### Update order
POST http://localhost:3000/api/auth/order/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTI5MTcwMmMxM2Q4OThhNjk5M2QyMjkiLCJmaXJzdF9uYW1lIjoiQW5pbCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJyZXlhbnNoQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTgyMDY0ODIxMiIsImlzX3ByaXZpbGFnZWQiOnRydWUsImlhdCI6MTY5ODM5NjI5MSwiZXhwIjoxNjk5MDAxMDkxfQ.RUvbrVJmoFHOShLHOtPnls04rLhNSHQAMk6-iUSGKiM

{
    "order_id" : "100002",
    "product_id" : "64f6da85ed30c8f3d5765043",
    "quantity" : 100,
    "total_price" : 12385,
    "grand_total" : 22130
}   
