
########## Branch API ##########

### 
    # Branch Details
###
GET  http://localhost:3000/api/auth/branch/nearest-branch
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTI5MTcwMmMxM2Q4OThhNjk5M2QyMjkiLCJmaXJzdF9uYW1lIjoiQW5pbCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJyZXlhbnNoQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTgyMDY0ODIxMiIsImlzX3ByaXZpbGFnZWQiOmZhbHNlLCJpYXQiOjE2OTgzNTM5MDcsImV4cCI6MTY5ODk1ODcwN30.JjgYRDsr-k-HfVnNFzEKgK86aL8xPaIPSv6pGbMZpZY

### 
    # Nearest Branch Product
###
GET  http://localhost:3000/api/auth/branch/branchProducts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTI5MTcwMmMxM2Q4OThhNjk5M2QyMjkiLCJmaXJzdF9uYW1lIjoiQW5pbCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJyZXlhbnNoQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTgyMDY0ODIxMiIsImlzX3ByaXZpbGFnZWQiOmZhbHNlLCJpYXQiOjE2OTgzNTM5MDcsImV4cCI6MTY5ODk1ODcwN30.JjgYRDsr-k-HfVnNFzEKgK86aL8xPaIPSv6pGbMZpZY

