
########## Branch API ##########

### 
    # Branch Details
###
GET  http://localhost:3000/api/auth/branch/nearest-branch
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiQW5pbCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGFAZGlzcG9zdGFibGUuY29tIiwicGhvbmUiOiI5ODcwODc4MDQwIiwiaWF0IjoxNjk2NzY0NjY1LCJleHAiOjE2OTczNjk0NjV9.NNdM9rWGbM4MNirKXc-o9aFLYKbGpSECsalPF5fBCN4

### 
    # Nearest Branch Product
###
GET  http://localhost:3000/api/auth/branch/branchProducts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiUmV5YW5zaCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGExQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTg3MDg3ODA0MCIsImlzX3ByaXZpbGFnZWQiOnRydWUsImlhdCI6MTY5NzQyOTY3NSwiZXhwIjoxNjk4MDM0NDc1fQ.u0OOwtNepb0txttDHfKKW5D_IWsYVgSsivIuHwL7EYY

