
########## Branch API ##########

### 
    # Branch Details
###
GET  http://35.154.189.224/api/auth/branch/nearest-branch
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTAxODFhYmY4NWU1MGNjMzQwNjdkZWQiLCJmaXJzdF9uYW1lIjoiRGVlcGFrIiwibGFzdF9uYW1lIjoiR3VwdGEiLCJlbWFpbCI6ImRlZXBha2d1cHRhQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTg3MDg3ODA0MSIsImlzX3ByaXZpbGFnZWQiOmZhbHNlLCJpYXQiOjE2OTk5MDk0NTMsImV4cCI6MTcwMDUxNDI1M30.nKjBxgOJCmxdJfQTUYgV63Vs7MDHwElvwP942ufKQas

### 
    # Nearest Branch Product
###
GET  http://localhost:3000/api/auth/branch/branchProducts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTAxODFhYmY4NWU1MGNjMzQwNjdkZWQiLCJmaXJzdF9uYW1lIjoiRGVlcGFrIiwibGFzdF9uYW1lIjoiR3VwdGEiLCJlbWFpbCI6ImRlZXBha2d1cHRhQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTg3MDg3ODA0MSIsImlzX3ByaXZpbGFnZWQiOmZhbHNlLCJpYXQiOjE2OTk5MDk0NTMsImV4cCI6MTcwMDUxNDI1M30.nKjBxgOJCmxdJfQTUYgV63Vs7MDHwElvwP942ufKQas

### 
    # Nearest Branch Delivery Fees
###
GET  http://localhost:3000/api/auth/branch/getDeliveryFees
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTAxODFhYmY4NWU1MGNjMzQwNjdkZWQiLCJmaXJzdF9uYW1lIjoiRGVlcGFrIiwibGFzdF9uYW1lIjoiR3VwdGEiLCJlbWFpbCI6ImRlZXBha2d1cHRhQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTg3MDg3ODA0MSIsImlzX3ByaXZpbGFnZWQiOmZhbHNlLCJpYXQiOjE2OTk5MDk0NTMsImV4cCI6MTcwMDUxNDI1M30.nKjBxgOJCmxdJfQTUYgV63Vs7MDHwElvwP942ufKQas

