###
    # Customer Login
###
POST http://35.154.189.224/api/auth/customer/login
Content-Type: application/json

{
    "phone" : "8850664191"
}

###
    # Verify OTP
###
POST http://35.154.189.224/api/auth/customer/verify-otp
Content-Type: application/json

{
    "phone" : "8850664191",
    "otp" : "2558"
}

### Registration
POST http://127.0.0.1:3000api/auth/customer/register
Content-Type: application/json

{
    "first_name": "Tes",
    "last_name": "TEst",
    "email": "test@joshfuels.com",
    "company": "TYS",
    "phone": "9210129012",
    "accept_term": "true"
}

### Get Profile
GET http://127.0.0.1:3000api/auth/customer/getProfile
Content-Type: application/json
Authorization: Bearer 

### Update Profile
POST http://127.0.0.1:3000api/auth/customer/updateProfile
Content-Type: application/json
Authorization: Bearer 

{    
    "first_name": "Anil"
}

### Update Profile Photo 
POST http://127.0.0.1:3000api/auth/customer/updatePhoto
Content-Type: application/json
Authorization: Bearer 

{    
    "first_name": "Anil"
}


### Add Address
POST http://35.154.189.224/api/auth/customer/add-address
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiUmV5YW5zaCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGExQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTg3MDg3ODA0MCIsImlzX3ByaXZpbGFnZWQiOnRydWUsImlhdCI6MTY5OTM0OTUzNiwiZXhwIjoxNjk5OTU0MzM2fQ.-TDyEwCHJXKBWqPTzjdHPe5Us97XRrENASTmSIq1G1g

{
    "address_type" : "Office", 
    "address_1" : "S-58, Haware Fantasia, Behind Inorbit Mall", 
    "area" : "Vashi", 
    "city" : "Navi Mumbai", 
    "pincode" : "123455", 
    "state" : "Maharashtra", 
    "country" : "India"
}

### Get Address
GET http://35.154.189.224/api/auth/customer/get-address
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiUmV5YW5zaCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGExQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTg3MDg3ODA0MCIsImlzX3ByaXZpbGFnZWQiOnRydWUsImlhdCI6MTY5OTM0OTUzNiwiZXhwIjoxNjk5OTU0MzM2fQ.-TDyEwCHJXKBWqPTzjdHPe5Us97XRrENASTmSIq1G1g

### Update Address
POST http://35.154.189.224/api/auth/customer/update-address
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiUmV5YW5zaCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGExQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTg3MDg3ODA0MCIsImlzX3ByaXZpbGFnZWQiOnRydWUsImlhdCI6MTY5OTM0OTUzNiwiZXhwIjoxNjk5OTU0MzM2fQ.-TDyEwCHJXKBWqPTzjdHPe5Us97XRrENASTmSIq1G1g

{
    "address_id" : "650191993bd8b22339022421",
    "address_type" : "Office", 
    "address_1" : "S-58, Haware Fantasia, Behind Inorbit Mall", 
    "area" : "Vashi", 
    "city" : "Navi Mumbai", 
    "pincode" : "000000", 
    "state" : "Maharashtra", 
    "country" : "India"
}

### Deleted Address 
DELETE http://35.154.189.224/api/auth/customer/delete-address
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiUmV5YW5zaCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGExQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTg3MDg3ODA0MCIsImlzX3ByaXZpbGFnZWQiOnRydWUsImlhdCI6MTY5OTM0OTUzNiwiZXhwIjoxNjk5OTU0MzM2fQ.-TDyEwCHJXKBWqPTzjdHPe5Us97XRrENASTmSIq1G1g

{
    "address_id" : "650191c73bd8b22339022427"
}

### Add Device
POST http://35.154.189.224/api/auth/customer/add-device
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiUmV5YW5zaCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGExQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTg3MDg3ODA0MCIsImlzX3ByaXZpbGFnZWQiOnRydWUsImlhdCI6MTY5OTM0OTUzNiwiZXhwIjoxNjk5OTU0MzM2fQ.-TDyEwCHJXKBWqPTzjdHPe5Us97XRrENASTmSIq1G1g

{
    "name" : "shivam's iPhone",
    "fcm_token" : "#12312412412412424124124" , 
    "type" : "iOS",
    "version" : "17.0.1"
}

### Fetch data 
Get http://35.154.189.224/api/auth/customer/userdata
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiUmV5YW5zaCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGExQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTg3MDg3ODA0MCIsImlzX3ByaXZpbGFnZWQiOnRydWUsImlhdCI6MTY5OTM0OTUzNiwiZXhwIjoxNjk5OTU0MzM2fQ.-TDyEwCHJXKBWqPTzjdHPe5Us97XRrENASTmSIq1G1g

### LogOut
POST http://35.154.189.224/api/auth/customer/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiUmV5YW5zaCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGExQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTg3MDg3ODA0MCIsImlzX3ByaXZpbGFnZWQiOnRydWUsImlhdCI6MTY5OTM0OTUzNiwiZXhwIjoxNjk5OTU0MzM2fQ.-TDyEwCHJXKBWqPTzjdHPe5Us97XRrENASTmSIq1G1g

### Send OTP to email 
POST http://35.154.189.224/api/auth/customer/send-otp
Content-Type: application/json

{
    "email" : "shivamrvgupta@gmail.com"
}

########## Branch API ##########

### 
    # Branch Details
###
GET  http://35.154.189.224/api/auth/branch/nearest-branch
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiUmV5YW5zaCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGExQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTg3MDg3ODA0MCIsImlzX3ByaXZpbGFnZWQiOnRydWUsImlhdCI6MTY5OTM0OTUzNiwiZXhwIjoxNjk5OTU0MzM2fQ.-TDyEwCHJXKBWqPTzjdHPe5Us97XRrENASTmSIq1G1g

### 
    # Nearest Branch Product
###
GET  http://35.154.189.224/api/auth/branch/branchProducts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiUmV5YW5zaCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGExQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTg3MDg3ODA0MCIsImlzX3ByaXZpbGFnZWQiOnRydWUsImlhdCI6MTY5OTM0OTUzNiwiZXhwIjoxNjk5OTU0MzM2fQ.-TDyEwCHJXKBWqPTzjdHPe5Us97XRrENASTmSIq1G1g


########## Cart API ##########

### 
    # Show Cart
###
GET  http://35.154.189.224/api/auth/cart/get
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiUmV5YW5zaCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGExQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTg3MDg3ODA0MCIsImlzX3ByaXZpbGFnZWQiOnRydWUsImlhdCI6MTY5OTM0OTUzNiwiZXhwIjoxNjk5OTU0MzM2fQ.-TDyEwCHJXKBWqPTzjdHPe5Us97XRrENASTmSIq1G1g

### 
    # Add To Cart
###
POST http://35.154.189.224/api/auth/cart/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiUmV5YW5zaCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGExQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTg3MDg3ODA0MCIsImlzX3ByaXZpbGFnZWQiOnRydWUsImlhdCI6MTY5OTM0OTUzNiwiZXhwIjoxNjk5OTU0MzM2fQ.-TDyEwCHJXKBWqPTzjdHPe5Us97XRrENASTmSIq1G1g 

{
    "product" : "64f6da5aed30c8f3d5765007",
    "quantity" : "15"
}

### 
    # Update Cart Data
###
POST http://35.154.189.224/api/auth/cart/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiUmV5YW5zaCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGExQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTg3MDg3ODA0MCIsImlzX3ByaXZpbGFnZWQiOnRydWUsImlhdCI6MTY5OTM0OTUzNiwiZXhwIjoxNjk5OTU0MzM2fQ.-TDyEwCHJXKBWqPTzjdHPe5Us97XRrENASTmSIq1G1g 

{
    "cart_id" : "6509f70778e25cf42012d7e8",
    "product_id" : "64f6da5aed30c8f3d5765007",
    "quantity" : 91
}

### 
    # Delete Single Cart Data
###
POST http://35.154.189.224/api/auth/cart/delete-item
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiUmV5YW5zaCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGExQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTg3MDg3ODA0MCIsImlzX3ByaXZpbGFnZWQiOnRydWUsImlhdCI6MTY5OTM0OTUzNiwiZXhwIjoxNjk5OTU0MzM2fQ.-TDyEwCHJXKBWqPTzjdHPe5Us97XRrENASTmSIq1G1g

{
    "cart_id" : "6509f70778e25cf42012d7e8",
    "product_id" : "64f6da5aed30c8f3d5765007"
}

### 
    # Delete Cart Data
###
DELETE http://35.154.189.224api/auth/cart/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGM5NjMxNzhmNWJmMTI2Njc3YzI0MmEiLCJmaXJzdF9uYW1lIjoiU2hpdmFtIiwibGFzdF9uYW1lIjoiR3VwdGEiLCJlbWFpbCI6ImFkbWluQGpvc2hmdWVscy5jb20iLCJwaG9uZSI6Ijg4NTA2NjQxOTEiLCJpc19wcml2aWxhZ2VkIjpmYWxzZSwiaWF0IjoxNjk3Nzg3MzY4LCJleHAiOjE2OTgzOTIxNjh9.9EfSXpEu7Z122TphENTVLOreHpvRTUiissbcDHu8R88

{
    "cart_id" : "651564f15b9479a09a6fcdf1"
    
}


###         # Order API  #       ###
## CREATE ORDER 
POST http://35.154.189.224/api/auth/order/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiUmV5YW5zaCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGExQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTg3MDg3ODA0MCIsImlzX3ByaXZpbGFnZWQiOnRydWUsImlhdCI6MTY5OTM0OTUzNiwiZXhwIjoxNjk5OTU0MzM2fQ.-TDyEwCHJXKBWqPTzjdHPe5Us97XRrENASTmSIq1G1g

{
    "address_id": "65003ac3957a312ef073de8e",
    "cart_id": "654a097679dcebf7531390d5",
    "delivery_date": "29/09/2023",
    "delivery_time": "2:00 - 10:00",
    "payment_method": "Cash on Delivery",
    "note": "Keep the Diesels extra on;y",
    "total_price" : 12340,
    "coupon_discount" : 100,
    "delivery_fee" : 300,
    "grand_total": 1334

}


### GeT ORDER 
GET http://35.154.189.224/api/auth/order/get
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiUmV5YW5zaCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGExQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTg3MDg3ODA0MCIsImlzX3ByaXZpbGFnZWQiOnRydWUsImlhdCI6MTY5OTM0OTUzNiwiZXhwIjoxNjk5OTU0MzM2fQ.-TDyEwCHJXKBWqPTzjdHPe5Us97XRrENASTmSIq1G1g

### GeT Single ORDER 
GET http://35.154.189.224/api/auth/order/get-order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiUmV5YW5zaCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGExQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTg3MDg3ODA0MCIsImlzX3ByaXZpbGFnZWQiOnRydWUsImlhdCI6MTY5OTM0OTUzNiwiZXhwIjoxNjk5OTU0MzM2fQ.-TDyEwCHJXKBWqPTzjdHPe5Us97XRrENASTmSIq1G1g

{
    "order_id" : "100002"
}



### Cancel order
POST http://35.154.189.224/api/auth/order/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiUmV5YW5zaCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGExQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTg3MDg3ODA0MCIsImlzX3ByaXZpbGFnZWQiOnRydWUsImlhdCI6MTY5OTM0OTUzNiwiZXhwIjoxNjk5OTU0MzM2fQ.-TDyEwCHJXKBWqPTzjdHPe5Us97XRrENASTmSIq1G1g

{
    "order_id" : "100002"
}

### Update order
POST http://35.154.189.224/api/auth/order/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiUmV5YW5zaCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGExQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTg3MDg3ODA0MCIsImlzX3ByaXZpbGFnZWQiOnRydWUsImlhdCI6MTY5OTM0OTUzNiwiZXhwIjoxNjk5OTU0MzM2fQ.-TDyEwCHJXKBWqPTzjdHPe5Us97XRrENASTmSIq1G1g

{
    "order_id" : "100002",
    "product_id" : "64f6da85ed30c8f3d5765043",
    "quantity" : 100,
    "total_price" : 12385,
    "grand_total" : 16446.88
}   

### Send Email
POST http://35.154.189.224/api/auth/customer/send-email
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiUmV5YW5zaCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGExQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTg3MDg3ODA0MCIsImlzX3ByaXZpbGFnZWQiOnRydWUsImlhdCI6MTY5OTM0OTUzNiwiZXhwIjoxNjk5OTU0MzM2fQ.-TDyEwCHJXKBWqPTzjdHPe5Us97XRrENASTmSIq1G1g



##### Delivery Mannn #######

###
    # DeliveryMan Login
###
POST http://35.154.189.224/api/auth/deliveryman/login
Content-Type: application/json

{
    "email": "deliveryman1@joshfuels.com",
    "password": "1234@user"
}

### Get Profile
GET http://35.154.189.224/api/auth/deliveryman/getProfile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiUmV5YW5zaCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGExQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTg3MDg3ODA0MCIsImlzX3ByaXZpbGFnZWQiOnRydWUsImlhdCI6MTY5OTM0OTUzNiwiZXhwIjoxNjk5OTU0MzM2fQ.-TDyEwCHJXKBWqPTzjdHPe5Us97XRrENASTmSIq1G1g

### Get Profile
GET http://35.154.189.224/api/auth/deliveryman/userdata
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiUmV5YW5zaCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGExQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTg3MDg3ODA0MCIsImlzX3ByaXZpbGFnZWQiOnRydWUsImlhdCI6MTY5OTM0OTUzNiwiZXhwIjoxNjk5OTU0MzM2fQ.-TDyEwCHJXKBWqPTzjdHPe5Us97XRrENASTmSIq1G1g

###
    # Get order 
###
GET http://35.154.189.224/api/auth/deliveryman/order/get
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiUmV5YW5zaCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGExQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTg3MDg3ODA0MCIsImlzX3ByaXZpbGFnZWQiOnRydWUsImlhdCI6MTY5OTM0OTUzNiwiZXhwIjoxNjk5OTU0MzM2fQ.-TDyEwCHJXKBWqPTzjdHPe5Us97XRrENASTmSIq1G1g

###
    # Get Single order 
###
GET http://35.154.189.224/api/auth/deliveryman/order/get-order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiUmV5YW5zaCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGExQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTg3MDg3ODA0MCIsImlzX3ByaXZpbGFnZWQiOnRydWUsImlhdCI6MTY5OTM0OTUzNiwiZXhwIjoxNjk5OTU0MzM2fQ.-TDyEwCHJXKBWqPTzjdHPe5Us97XRrENASTmSIq1G1g

{
    "order_id" : "100009"
}

###
    # Get Previous order 
###
GET http://35.154.189.224/api/auth/deliveryman/order/previous-order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiUmV5YW5zaCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGExQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTg3MDg3ODA0MCIsImlzX3ByaXZpbGFnZWQiOnRydWUsImlhdCI6MTY5OTM0OTUzNiwiZXhwIjoxNjk5OTU0MzM2fQ.-TDyEwCHJXKBWqPTzjdHPe5Us97XRrENASTmSIq1G1g


###
    # Update Delivery Status 
###
POST http://35.154.189.224/api/auth/deliveryman/order/update-status
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiUmV5YW5zaCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGExQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTg3MDg3ODA0MCIsImlzX3ByaXZpbGFnZWQiOnRydWUsImlhdCI6MTY5OTM0OTUzNiwiZXhwIjoxNjk5OTU0MzM2fQ.-TDyEwCHJXKBWqPTzjdHPe5Us97XRrENASTmSIq1G1g

{
    "order_id": "100009",
    "status" : "Confirmed"
}


###
    # Update Payment Status 
###
POST http://35.154.189.224/api/auth/deliveryman/order/update-payment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiUmV5YW5zaCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGExQGRpc3Bvc3RhYmxlLmNvbSIsInBob25lIjoiOTg3MDg3ODA0MCIsImlzX3ByaXZpbGFnZWQiOnRydWUsImlhdCI6MTY5OTM0OTUzNiwiZXhwIjoxNjk5OTU0MzM2fQ.-TDyEwCHJXKBWqPTzjdHPe5Us97XRrENASTmSIq1G1g

{
    "order_id": "100009",
    "status" : "Paid"
}